### ISSUE TITLE
Light/dark mode bug

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2880]

**Comment by AnaSasso** [comment]
There's a bug when changing the language it also changes the mode, is this it @EPajares

**Comment by nihar1024** [comment]
@majkshkurti I think this has been fixed, right? Should we close it?

**Comment by majkshkurti** [comment]
@nihar1024 I still get this issue sometimes. We can leave it open

**Comment by nihar1024** [comment]
Has been moved here:
https://github.com/goat-community/goat/issues/3418
